=== darrexx/jrpg-helper/src/lib/forms/uniqueMonster/uniqueMonster.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://jrphelper.moe/uniqueMonster.schema.json",
  "title": "uniqueMonster",
  "description": "UniqueMonsters for a Game",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "level": {
        "type": "integer"
      },
      "map": {
        "type": "string"
      },
      "location": {
        "type": "string"
      },
      "x": {
        "type": "string"
      },
      "y": {
        "type": "string"
      },
      "z": {
        "type": "string"
      },
      "wikiLink": {
        "type": "string"
      },
      "spawnTime": {
        "type": "string"
      }
    },
    "required": ["name", "map"]
  }
}

=== darrexx/jrpg-helper/src/lib/forms/uniqueMonster/example.json
[
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY1",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY2",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY3",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY4",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY5",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY6",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  {
    "name": "ABCDEFGHIJKLMNOPQRSTUVWXY7",
    "map": "ABCDEFGHIJKLMNOPQRST",
    "level": 0,
    "location": "ABCD",
    "x": "0.01",
    "y": "0.01",
    "z": "0.01",
    "wikiLink": "ABCDEFGHI",
    "spawnTime": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  }
]
